In [4]:
pip install numpy

     |████████████████████████████████| 15.7MB 1.4MB/s eta 0:00:01
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
print(arr.shape)

(9,)


In [10]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])

In [12]:
print(arr2d)
print(arr2d.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [14]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[10, 2, 3], [4, 5, 6]]])


In [16]:
print(arr3d)
print(arr3d.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[10  2  3]
  [ 4  5  6]]]
(2, 2, 3)


In [18]:
reshapeArr = arr.reshape(3,3)

In [22]:
print(reshapeArr)
print(reshapeArr.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [24]:
reshapeArr = arr2d.reshape(-1)
print(reshapeArr)
print(reshapeArr.shape)

[1 2 3 4 5 6]
(6,)


In [29]:
search = np.where(arr == 9)
print(search)

(array([8]),)


In [31]:
arrDes = np.array([1,4,7,56,34,0,-1,45,-5,-2,99])
print(np.sort(arrDes))

[-5 -2 -1  0  1  4  7 34 45 56 99]


In [34]:
arrNombres = np.array(['Pedro','Juan','Santiago','Lucas','Alberto'])
print(np.sort(arrNombres))

['Alberto' 'Juan' 'Lucas' 'Pedro' 'Santiago']


In [37]:
filtro = arr > 5
newArr = arr[filtro]
print(filtro)
print(newArr)

[False False False False False  True  True  True  True]
[6 7 8 9]


In [40]:
print(np.arange(0, 100, 2))

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


In [41]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, like=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.
    
    Parameters
    ----------
    start : integer or real, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : integer or real
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off 